apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterevents.kopf.dev
spec:
  scope: Cluster
  group: kopf.dev
  names:
    kind: ClusterEvent
    plural: clusterevents
    singular: clusterevent
    shortNames:
      - ces
      - ce
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
